data_ingestion:
    name: 'DataIngestor'
    dataset: 'Heart_Failure_Prediction_Dataset'
    data_source: 'https://github.com/entbappy/Branching-tutorial/raw/master/winequality-data.zip'

train_test_split:
    name: 'RandomTrainTestSplitter'
    label: 'quality'
    test_size: 0.25

data_preparation:
    - name: 'StandardScalerSK'
      features: 
        - 'fixed acidity'
        - 'volatile acidity'
      checkpoint: True
    - name: 'StandardScalerSK'
      features: 
        - 'citric acid'
      checkpoint: True


model:
    name: 'RidgeRULPredictor'
    device: 'cpu'

evaluation:
    - name: 'MSE'

